spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/lullaby
#    username: lullaby
#    password: lullaby
    driver-class-name: org.h2.Driver
    +url: jdbc:h2:mem:test
    #url: jdbc:h2:tcp://localhost:8082/test
    username: sa
    password:
#  h2:
#    console:
#      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
#      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
